sudo: required
services:
  - docker

before_install:
  - docker build -t ssamantray/travis-ci -f Dockerfile.dev .
  
script:
  - docker run -e CI=true ssamantray/travis-ci npm run test

language: generic 